"""
training/paraphrases.py

Hand-written natural paraphrases, one bank per intent.

Why this exists: `templates.py` expands ~250 base utterances into ~5000 rows by
attaching prefixes and suffixes. That inflates row count without adding lexical
diversity, and the model plateaued at 0.71 on the held-out set because of it.
Real generalisation needs genuinely different *wordings*, which is what this
file supplies.

IMPORTANT -- no leakage: none of these lines duplicate `eval_set.py`. The eval
set stays a true holdout, otherwise its score would be meaningless. Different
verbs, different entities, different sentence shapes on purpose.
"""

from __future__ import annotations

PARAPHRASES: dict[str, list[str]] = {
    "smalltalk.greeting": [
        "hiya", "hey", "howdy", "hello there", "good afternoon", "sup",
        "anyone home", "you awake", "hey buddy", "greetings", "hello jarvis",
        "start up", "you online", "morning jarvis", "evening", "hi again",
        "long time no see", "back again", "hey assistant", "knock knock",
    ],
    "smalltalk.thanks": [
        "thank you", "thanks heaps", "much appreciated", "brilliant thanks",
        "that helped a lot", "you are a lifesaver", "spot on thank you",
        "exactly what i needed", "grateful for that", "well done",
        "awesome thank you", "lovely stuff", "that did the trick",
        "cool thanks", "thanks again", "many thanks", "you rock",
        "appreciate the help", "sorted thanks", "great thanks",
        # Very short chat abbreviations. Two-character inputs give the model
        # almost no features, so they need to be seen explicitly.
        # "ty" itself is deliberately absent: it lives in the held-out eval set,
        # so training on it would invalidate that benchmark. These siblings teach
        # the same short-abbreviation shape without touching the holdout.
        "tysm", "thx", "thnx", "tnx", "ta", "cheers", "cheers mate", "tq",
        "nice one", "legend", "perfect", "great stuff", "smashing",
    ],
    "smalltalk.bye": [
        "goodbye", "bye bye", "see ya", "later", "im leaving now",
        "signing off", "thats all for now", "we are done", "end session",
        "goodnight jarvis", "have a good one", "until next time",
        "im heading out", "shutting you down", "talk soon", "peace out",
        "thats it for today", "closing up", "adios", "farewell",
    ],
    "smalltalk.identity": [
        "introduce yourself", "what should i call you", "are you a robot",
        "are you human", "who built you", "who created you",
        "what kind of ai are you", "are you chatgpt", "whats your identity",
        "describe yourself", "are you sentient", "what are you exactly",
        "tell me who you are", "your name please", "are you real",
        "what powers you", "which model do you use", "are you local or cloud",
    ],
    "smalltalk.capabilities": [
        "what are you good at", "list what you can do", "show your abilities",
        "what features do you have", "how can you help me",
        "what tasks can you handle", "what should i ask you",
        "give me some examples", "what are my options", "menu",
        "what do you support", "capabilities please", "how do you work",
        "what can i use you for", "any tips on using you",
        "what else can you do", "your skills", "options",
    ],
    "info.factual": [
        "how tall is the burj khalifa", "what causes thunder",
        "who discovered penicillin", "how many continents are there",
        "what is the largest ocean", "when was the printing press invented",
        "why do birds migrate", "how fast does light travel",
        "what is the boiling point of water", "who painted the mona lisa",
        "how far is mars from earth", "what is the smallest country",
        "how many planets orbit the sun", "what language is spoken in brazil",
        "who wrote hamlet", "how long is the amazon river",
        "what is the hottest desert", "when did the berlin wall fall",
        "how does the heart pump blood", "why is the ocean salty",
        "what are volcanoes made of", "how do birds fly",
        "tell me about ancient egypt", "explain the water cycle",
        "what happened in 1969", "who led the indian independence movement",
        "what is the tallest tree", "how many countries are in africa",
        "describe the solar system", "what is a supernova",
        "how do magnets work", "why do we dream",
        "what is the currency of japan", "who is the author of the ramayana",
        # Causal "why do ..." science questions whose vocabulary overlaps the
        # weather bank (seasons, rain, temperature, snow). Without these,
        # genuine explanation requests were pulled over to info.weather, which
        # is a live forecast lookup and a completely different capability.
        "why do trees lose their leaves in winter",
        "why does it rain more near the equator",
        "why do the seasons change at all",
        "what causes the seasons on earth",
        "why is snow white",
        "how do clouds actually form",
        "why does thunder follow lightning",
        "what makes the sky blue during the day",
        "why do some animals hibernate in the cold",
        "how does temperature affect plant growth",
        "why do deserts get so cold at night",
        "what causes monsoon winds to reverse",
        "why do flowers bloom in spring",
        "how does the greenhouse effect work",
        "why is the arctic colder than the antarctic",
        "why does ice float on water",
        "what causes the tides",
    ],
    "info.definition": [
        "define resilience", "what does altruism mean", "meaning of candid",
        "define the term latency", "whats a synonym for happy",
        "explain the word verbose", "define throughput",
        "what does concurrency mean", "meaning of the word arduous",
        "define idempotent", "what does mitigate mean",
        "give me the definition of nuance", "define lucid",
        "what is the meaning of tenacity", "define brevity",
        "spell out what recursion means", "define anomaly",
    ],
    "info.news": [
        "whats going on today", "current affairs please", "news update",
        "any breaking news", "whats trending", "headlines please",
        "catch me up on the news", "whats in the papers",
        "give me a news briefing", "latest developments",
        "recent events summary", "news about the economy",
        "sports roundup", "tech news today", "whats happening in politics",
        "anything new in science", "todays top story", "news digest",
    ],
    "info.weather": [
        "hows the weather", "weather report", "is it sunny out",
        "do i need a jacket", "whats the temperature",
        "any chance of snow tomorrow", "humidity levels today",
        "wind speed right now", "is it foggy outside", "weather this weekend",
        "will it be hot today", "rain expected later",
        "whats the forecast looking like", "climate right now",
        "should i carry an umbrella", "how windy is it",
        "temperature tonight", "is a storm coming",
    ],
    "info.math": [
        "whats 12 plus 34", "multiply 9 by 8", "divide 144 by 12",
        "20 percent of 500", "cube of 7", "what is 2 to the power 8",
        "sum of 1 through 100", "average of 4 8 and 12",
        "subtract 19 from 60", "how much is 6 times 7",
        "whats half of 350", "compute 99 minus 44",
        "raise 3 to the fifth", "give me the factorial of 6",
        "whats the remainder of 17 divided by 5", "double 128",
        "one third of 900", "whats 5 squared",
    ],
    "info.time": [
        "current time please", "tell me the date", "what year is it",
        "which day of the week is it", "time check",
        "how many hours until midnight", "whats the time right now",
        "todays date please", "what month are we in",
        "how many days left in the year", "is it morning or evening",
        "give me the timestamp", "what week number is it",
        "days until my next birthday", "clock",
    ],
    "info.translate": [
        "translate hello into italian", "how do you say water in russian",
        "put this into chinese", "translate thanks to dutch",
        "spanish for good night", "what is book in german",
        "convert this sentence to french", "say welcome in swahili",
        "translate please into polish", "hindi for friend",
        "how to say sorry in japanese", "turn this into greek",
        "translate my message to turkish", "urdu for mother",
    ],
    "info.currency": [
        "convert 20 dollars to euros", "how many rupees is 10 pounds",
        "exchange rate usd to yen", "whats 1000 yen in dollars",
        "convert cad to inr", "value of a euro in rupees",
        "how much is 5 bitcoin in usd", "swap 250 chf to gbp",
        "currency conversion 90 aud to nzd", "dollar rate today",
    ],
    "media.image_search": [
        "show me a photo of a tiger", "find an image of the pyramids",
        "i want to see pictures of mount fuji", "display photos of venice",
        "get pictures of a hummingbird", "look up images of the colosseum",
        "show me how a platypus looks", "photos of the sahara please",
        "find a picture of a lighthouse", "images of autumn forests",
        "show me a shot of the milky way", "picture of a bengal cat",
        "see some photos of iceland waterfalls", "find snaps of old trains",
        "show me a portrait of shakespeare", "give me photos of coral reefs",
        "i want to look at pictures of tulips", "show me an image of jupiter",
    ],
    "media.image_generate": [
        "create an image of a robot chef", "generate a picture of a floating island",
        "draw me a cyberpunk street", "make art of a phoenix rising",
        "design a poster for a coffee shop", "render a sunset over mountains",
        "create a wallpaper with geometric shapes",
        "generate a logo with a wolf", "paint a surreal desert scene",
        "make an illustration of a steampunk airship",
        "produce an image of a glass castle", "create concept art for a spaceship",
        "draw a cartoon fox in a hat", "generate a minimalist book cover",
        "invent an image of a crystal forest", "compose art of a rainy tokyo alley",
        "make me a picture of a dragonfly robot",
    ],
    "media.video_search": [
        "find a video about volcanoes", "play a clip on how engines work",
        "search youtube for guitar lessons", "show me a documentary on sharks",
        "find footage of the moon landing", "play a song video",
        "look for a tutorial on excel", "find a talk about productivity",
        "show me a recipe video", "play something about space exploration",
    ],
    "action.open_app": [
        "open word", "start photoshop", "launch discord", "run steam",
        "open my email client", "boot up slack", "start the music player",
        "open task manager", "launch the browser", "open excel",
        "start zoom", "run the terminal", "open my code editor",
        "launch obs", "open the photos app", "start telegram",
        "open the app store", "run disk cleanup", "open control panel",
    ],
    "action.web_open": [
        "open stackoverflow", "visit amazon", "go to netflix",
        "navigate to bbc news", "open my gmail inbox in the browser",
        "load twitter", "browse to wikipedia homepage",
        "open the vercel dashboard", "go to hacker news",
        "visit the python docs site", "open google maps in a tab",
        "take me to spotify web", "launch the youtube website",
    ],
    "action.system_control": [
        "shut down", "power off the pc", "restart now", "log me out",
        "sleep the computer", "raise the brightness", "dim the screen",
        "unmute audio", "max the volume", "disable bluetooth",
        "enable dark mode on the system", "hibernate",
        "turn the wifi back on", "set volume to 50 percent",
        # Device nouns with a possessive ("my laptop", "my pc") were being read
        # as questions about stored personal data rather than machine control.
        "lock the laptop", "lock my pc", "lock my machine",
        "put my computer to sleep", "shut my laptop down",
        "restart my pc now", "reboot this desktop",
        "turn my computer off", "wake my laptop up",
        "sign me out of my pc",
    ],
    "action.screenshot": [
        "screenshot", "snap the screen", "capture the display",
        "take a screen grab", "save a picture of my screen",
        "screengrab this", "photograph the screen", "capture this window",
        "get a shot of whats showing", "print screen",
    ],
    "memory.remember": [
        "remember my dog is called rex", "store that i use vim",
        "note down that my flat number is 12b",
        "keep this in mind i hate coriander",
        "remember i prefer tea over coffee",
        "save that my gym day is monday",
        "log that my sister lives in leeds",
        "memorise my shoe size is 9",
        "hold on to this my wifi is called skynet",
        "remember im learning spanish",
        "note that my car is a blue hatchback",
        "please store my nickname as sam",
    ],
    "memory.recall": [
        "what have you stored about me", "tell me what you remember",
        "list my saved details", "whats my dogs name",
        "do you know where i work", "remind me what i said about coffee",
        "read back my preferences", "what facts do you hold on me",
        "show my profile", "any notes about me",
        "what did i ask you to remember", "my saved info please",
    ],
    "memory.forget": [
        "forget my address", "delete the note about my dog",
        "clear my stored preferences", "remove what you know about my job",
        "erase everything about me", "drop that memory",
        "unsave my nickname", "wipe my profile",
        "forget what i told you yesterday", "delete my saved city",
    ],
    "task.plan": [
        "help me plan a trip to japan", "outline steps to start a blog",
        "build me a workout schedule", "organise my move to a new flat",
        "draft a plan for launching a podcast",
        "how should i approach learning to cook",
        "make a checklist for a house party",
        "structure my revision for finals",
        "plan a product launch timeline",
        "break down writing a dissertation",
        "give me a roadmap for becoming a designer",
        "help me schedule my month",
        "sketch out a plan to save money",
        "steps to organise a charity run",
    ],
    "task.code": [
        "write a function to sort a dictionary by value",
        "how do i read a csv in python",
        "fix my off by one error in this loop",
        "explain this traceback to me",
        "generate a sql query for top customers",
        "refactor this into smaller functions",
        "write a bash script to back up a folder",
        "why does my async function return none",
        "create a react component for a modal",
        "help me write a unit test for this class",
        "convert this javascript to typescript",
        "optimise this nested loop",
        "write a regex to match phone numbers",
        "debug my api call that returns 401",
        # "whats wrong with my ..." is the most natural way to ask for a code
        # review, but the possessive "my" made the model read it as a request to
        # recall something it had stored about the user.
        "whats wrong with my function",
        "whats wrong with my sql query",
        "whats broken in my code",
        "why is my loop not terminating",
        "why does my script crash on startup",
        "find the bug in my class",
        "review my implementation for mistakes",
        "my regex isnt matching what did i do wrong",
        "whats the issue with my import statement",
        "my test keeps failing can you look",
        "why is my variable undefined here",
        "spot the error in my snippet",
    ],
    "doc.write": [
        "write a business proposal for a bakery",
        "draft a leave application",
        "compose a project summary document",
        "create a one page brief on solar energy",
        "write meeting notes from these points",
        "prepare a formal complaint letter",
        "draft a press release for our app",
        "write an executive summary",
        "produce a technical spec for the api",
        "make me a case study outline",
        "write a scholarship application essay",
    ],
    "doc.read": [
        "summarise this document",
        "what are the main points of this file",
        "read the attached report",
        "extract the tables from this pdf",
        "give me a tldr of this paper",
        "pull the dates out of this contract",
        "what does the attachment contain",
        "review this document for me",
        "find the conclusion in this pdf",
        "condense this file into bullets",
        # "whats in this attached ..." overlapped vision.analyze, which handles
        # images. The distinguishing cue is the document noun, not the verb.
        "whats in this attached document",
        "whats inside this pdf",
        "whats in the attached file",
        "tell me whats in this docx",
        "open the attached pdf and explain it",
        "go through this attachment for me",
        "what does this spreadsheet contain",
        "check the attached report and summarise",
    ],
    "vision.analyze": [
        "what does this image show",
        "identify the object in this photo",
        "transcribe the text in this screenshot",
        "how many people are in this picture",
        "what colour is the car in this image",
        "explain this diagram",
        "read this handwritten note",
        "is there a dog in this photo",
        "analyse this graph image",
        "whats written on this sign",
        "caption this picture for me",
    ],
    "web.browse": [
        "search the internet for hotel deals",
        "google the best laptops of this year",
        "find sources on renewable energy costs",
        "look up the wikipedia page for saturn",
        "research electric car prices",
        "browse for reviews of this restaurant",
        "check online what time the shop closes",
        "find the official docs for fastapi",
        "search for tutorials on woodworking",
        "get me articles about sleep science",
        "read this website and tell me the gist",
        "look on the web for flight prices",
        # "look online/up for <product> reviews" was being read as an image
        # request because "look" plus a product name overlaps the image bank.
        "look online for reviews of a laptop",
        "look online for the cheapest deal",
        "search online for phone comparisons",
        "find reviews of this camera on the web",
        "check the web for customer ratings",
        "look up product reviews",
        "search the web for benchmark results",
        "find online opinions about this brand",
        # "fetch/grab this page and summarise" -- the trailing polite-sounding
        # verb was dragging these toward smalltalk.
        "fetch this page and summarise",
        "grab that page and give me the gist",
        "pull up this link and condense it",
        "open this url and summarise the content",
        "read that article and shorten it",
        "scrape this page for the key points",
        "fetch the page contents",
        "get this webpage and explain it",
    ],
    "email.draft": [
        "write an email to hr about my payslip",
        "draft a follow up message to a recruiter",
        "compose a polite decline to an invitation",
        "email my landlord about a repair",
        "write a reminder email to the team",
        "draft an apology email to a customer",
        "prepare an introduction email to a client",
        "write a resignation email",
        "compose an email requesting a refund",
        "draft a message asking for feedback",
    ],
}


def rows() -> list[tuple[str, str]]:
    """Flattens the bank into labelled (text, intent) rows."""
    out: list[tuple[str, str]] = []
    for intent, lines in PARAPHRASES.items():
        for line in lines:
            out.append((line, intent))
    return out
