"use client";
import * as Dialog from "@radix-ui/react-dialog";
import { useEffect, useState } from "react";
import { useUIStore } from "../../store/ui-store";
// Every module reachable from the sidebar belongs here too -- the palette listed
// only five of them, so Ctrl+K could not reach Neural Nexus, Workforce, the
// Knowledge Graph or Security at all.
const commands = [{ label: "Open Chat", target: "chat" }, { label: "Open Mission Control", target: "mission-control" }, { label: "Open Neural Nexus 3D", target: "neural-nexus" }, { label: "Open Operations Center", target: "operations" }, { label: "Open Development Studio", target: "development-studio" }, { label: "Open AI Studio", target: "ai-studio" }, { label: "Open Workforce Swarm", target: "agents" }, { label: "Open Knowledge Graph", target: "knowledge" }, { label: "Open Security Framework", target: "security" }, { label: "Open Settings", target: "settings" }] as const;
export function CommandPalette() { const { paletteOpen, setPaletteOpen, setActive } = useUIStore(); const [query, setQuery] = useState(""); useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setPaletteOpen(true); } }; addEventListener("keydown", handler); return () => removeEventListener("keydown", handler); }, [setPaletteOpen]); const visible = commands.filter(command => command.label.toLowerCase().includes(query.toLowerCase())); return <Dialog.Root open={paletteOpen} onOpenChange={setPaletteOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="command-palette"><Dialog.Title>Command palette</Dialog.Title><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search pages and commands" aria-label="Search commands"/>{visible.map(command => <button key={command.target} onClick={() => { setActive(command.target); setPaletteOpen(false); setQuery(""); }}>{command.label}</button>)}{visible.length === 0 && <p>No available commands match this search.</p>}<p>Use Ctrl + K anywhere.</p></Dialog.Content></Dialog.Portal></Dialog.Root>; }
